config/routes.rb
Rails.application.routes.draw do
 root 'pages#new'

 get 'pages/home' => 'pages#home'
 get 'pages/show' => 'pages#show'
 get 'pages/index' => 'pages#index'

  resources :pages

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def new
    @page=Page.new
  end

  def create
    @page=Page.new(page_params)
    if @page.save
      redirect_to @page
    else
      render :new
    end
  end

  def show
    @page = Page.find(params[:id])
  end

  def home
  end

  def index
    @pages=Page.all
  end

  private
    def page_params
      params.require(:page).permit!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def nav_link_to(click_text, action, url, style)
		if action_name == action
			return link_to click_text, url, class: style
		else
			return link_to click_text, url
		end
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
		<section id="footer-area">

			<section id="footer-outer-block">
					<aside class="footer-segment">
							<h4>Friends</h4>
								<ul>
									<li><a href="#">one linkylink</a></li>
									<li><a href="#">two linkylinks</a></li>
									<li><a href="#">three linkylinks</a></li>
								</ul>
					</aside><!-- end of #first footer segment -->

					<aside class="footer-segment">
							<h4>Awesome Stuff</h4>
								<ul>
									<li><a href="#">one linkylink</a></li>
									<li><a href="#">two linkylinks</a></li>
									<li><a href="#">three linkylinks</a></li>
								</ul>
					</aside><!-- end of #second footer segment -->

					<aside class="footer-segment">
							<h4>Coolness</h4>
								<ul>
									<li><a href="#">one linkylink</a></li>
									<li><a href="#">two linkylinks</a></li>
									<li><a href="#">three linkylinks</a></li>
								</ul>
					</aside><!-- end of #third footer segment -->
					
					<aside class="footer-segment">
							<h4>Blahdyblah</h4>
								<p>&copy; 2010 <a href="#">yoursite.com</a> Praesent libero. Sed cursus ante dapibus diam. Sed nisi.</p>
					</aside><!-- end of #fourth footer segment -->

			</section><!-- end of footer-outer-block -->

		</section><!-- end of footer-area -->
	</footer>

app/views/layouts/_header_nav.html.erb
<header><!-- header -->
		<h1>Speeding Through Life</h1>
		<h2>Where do you think you are going?</h2>
		<%=image_tag "headerimg.jpg", size: "940x200"%>
 	</header><!-- end of header -->
	
	<nav><!-- top nav -->
		<div class="menu">
			<ul>
				<li><%= nav_link_to "Home", "home", pages_home_path, "current_page"%></li>
				<li><%= nav_link_to "New Page","new", root_path, "current_page" %></li>

				<li><%= nav_link_to "Index", "index", pages_index_path, "current_page" %></li>
			</ul>
		</div>
	</nav><!-- end of top nav -->

app/views/layouts/_sidebar.html.erb
<aside id="sidebar1"><!-- sidebar1 -->
				<h3>Things To Do</h3>
					<ul>
						<li><a href="#">Play Games</a></li>
						<li><a href="#">Chat With Friends</a></li>
						<li><a href="#">Swap Stories</a></li>
						<li><a href="#">Sell Stuff</a></li>
						<li><a href="#">Buy Stuff</a></li>
						<li><a href="#">Trade Stuff</a></li>
					</ul>
					
				<h3>Sponsors</h3>
				<%= image_tag "ad125.jpg"%><br /><%=image_tag "ad125.jpg"%><br /><br />

				<h3>Related Articles</h3>
					<ul>
						<li><a href="#">Curabitur sodales</a></li>
						<li><a href="#">Sed dignissim</a></li>
						<li><a href="#">Fusce nec</a></li>
						<li><a href="#">Curabitur sodales</a></li>
						<li><a href="#">Sed dignissim</a></li>
						<li><a href="#">Fusce nec</a></li>
					</ul>

				<h3>Connect With Us</h3>
					<ul>
						<li><a href="#">Twitter</a></li>
						<li><a href="#">Facebook</a></li>
					</ul>

		</aside><!-- end of sidebar1 -->

		<aside id="sidebar2"><!-- sidebar2 -->
				<h3>Stuff</h3>
					<ul>
						<li><a href="#">Curabitur sodales</a></li>
						<li><a href="#">Sed dignissim</a></li>
						<li><a href="#">Fusce nec</a></li>
						<li><a href="#">Nulla quis</a></li>
					</ul>

				<h3>More Stuff</h3>
					<ul>
						<li><a href="#">Blah, blah and all blah</a></li>
						<li><a href="#">More blah</a></li>
					</ul>

				<h3>S'more Goodies</h3>
					<ul>
						<li><a href="#">Curabitur sodales</a></li>
						<li><a href="#">Sed dignissim</a></li>
						<li><a href="#">Fusce nec</a></li>
						<li><a href="#">Nulla quis</a></li>
						<li><a href="#">Curabitur sodales</a></li>
						<li><a href="#">Sed dignissim</a></li>
						<li><a href="#">Fusce nec</a></li>
						<li><a href="#">Nulla quis</a></li>
					</ul>

				<h3>Did You Know?</h3>
					<ul>
						<li><a href="#">Curabitur sodales</a></li>
						<li><a href="#">Sed dignissim</a></li>
						<li><a href="#">Fusce nec</a></li>
						<li><a href="#">Nulla quis</a></li>
						<li><a href="#">Curabitur sodales</a></li>
						<li><a href="#">Sed dignissim</a></li>
						<li><a href="#">Fusce nec</a></li>
						<li><a href="#">Nulla quis</a></li>
					</ul>

				<h3>FAQ</h3>
					<ul>
						<li><a href="#">Curabitur sodales</a></li>
						<li><a href="#">Sed dignissim</a></li>
						<li><a href="#">Fusce nec</a></li>
						<li><a href="#">Nulla quis</a></li>
						<li><a href="#">Curabitur sodales</a></li>
						<li><a href="#">Sed dignissim</a></li>
						<li><a href="#">Fusce nec</a></li>
						<li><a href="#">Nulla quis</a></li>
					</ul>

		</aside><!-- end of sidebar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
  <title>Session172formhelper</title>
  <%= stylesheet_link_tag  'application', media: 'screen', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  	<!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>
<body>
	<div id="wrapper">
		<%= render 'layouts/header_nav.html.erb'%>
		<%= yield %>
		<%= render 'layouts/sidebar.html.erb'%>
		<%= render 'layouts/footer.html.erb'%>
	</div>
</body>
</html>

app/views/pages/home.html.erb
<section id="content"><!-- #content -->
	<article>
		<p>Problem Statement : Have Rails Appliction with HTML layout & List all the form helpers.</p>
		<h2>Form Helpers</h2>
		<p>Rails provides a series of helpers for generating form elements such as checkboxes, text fields, and radio buttons.<br> These basic helpers, with names ending in _tag (such as text_field_tag and check_box_tag), generate just a single input element.</p> <p>The first parameter to these is always the name of the input. When the form is submitted, the name will be passed along with the form data, and will make its way to the params in the controller with the value entered by the user for that field.</p>
		<p>Some of the form helpers are:</p>
	
		<p>check_box_tag</p>
		<p>label_tag</p>
		<p>radio_button_tag</p>
		<p>text_area_tag</p>
		<p>password_field_tag</p>
		<p>hidden_field_tag</p>
		<p>search_field</p>
		<p>telephone_field</p>
		<p>date_field</p>
		<p>datetime_local_field</p>
		<p>month_field</p>
		<p>week_field</p>
		<p>url_field</p>
		<p>email_field</p>
		<p>color_field</p>
		<p>time_field</p>
		<p>number_field</p>
		<p>range_field</p>
	</article>							
</section><!-- end of #content -->

app/views/pages/index.html.erb
<section id="content"><!-- #content -->
	<article>
		<h2>List of Pages</h2>
		<ul>
			<% @pages.each do |p|%>
			<li><%=p.title%><br>
					<%=p.description%> </li><br>
					<%end%>
		</ul>
	</article>
</section><!-- end of #content -->

app/views/pages/new.html.erb
<section id="content"><!-- #content -->
	<article>
		<h2>Create a new Page</h2>

<%= form_for @page do |p|%>
	<p><%=p.label :title%>
	<%=p.text_field :title%></p>

	<p><%=p.label :description, "Desc"%>
	<%= p.text_area :description%></p>
	<%=p.submit%>
<%end%>
</article>
</section><!-- end of #content -->

app/views/pages/show.html.erb
<section id="content"><!-- #content -->
	<article>
		<h2><%=@page.title%></h2>
		<p><%=@page.description%></p>
	</article>
							
</section><!-- end of #content -->